### ISSUE TITLE
Vim-Ruby insists on using system ruby

### ISSUE THREAD

**Issue by mercutiomontague** [tpope/vim-rbenv#6]
Hey Tim,

I installed vim-gnome on Ubuntu 14.10 and also pathogen and vim-rbenv plugin.  I checked on the ruby version with the following and it appears my rbenv installs are not being referenced...

nnoremap <localleader>z <SID>RubyPath()<cr>

function! s:RubyPath()
ruby << EOF
puts $:
EOF
endfunction

**Comment by tpope** [comment]
The vim ruby interface is is linked at compile time and can't be changed.
